### ISSUE TITLE
Loglia Landing Page

### ISSUE THREAD

**Issue by cwhite92** [jackmcdade/five-minute-feedback#1]
Hi Jack!

This is a fantastic idea and thank you for spending the time doing these :)

Would appreciate some quick feedback on the landing page for Loglia: https://www.loglia.app/

It just looks pretty bland, bare-bones and generic. I'd love it to "pop" more and be kinda quirky so it stands out from the crowd but every time I try I feel like it goes in the wrong direction and just starts to look ugly instead. You have a very cool looking and memorable style and I'd love to apply some of those traits to it!

**Comment by jackmcdade** [comment]
You've been feedbacked! https://youtu.be/u8jsCJVo_ek
