### ISSUE TITLE
PointsBox Homepage

### ISSUE THREAD

**Issue by leeovery** [jackmcdade/five-minute-feedback#4]
Hey!

[PointsBox.com](https://pointsbox.com)

Would love some general feedback on the top 1/3 mainly. I did this myself and I know it’s under selling the system. I’m a better developer than designer lol. 

I think I like some ideas on how to better showcase what the site is about. How it works. Why users should care etc. 

I actually have a decent conversion rate on the homepage. But I don’t feel it’s putting the best foot forward. It looks a little amateur perhaps. Or at the very least boring. 

Sorry if that’s vague. I’m not really sure how to improve it at the moment. All my time has been spent on building a solid system. But before scaling I’d love to nail the homepage design with something amazing and fun and modern and cool!! 😅

Cheers!!!
Lee

**Comment by jackmcdade** [comment]
Hey Lee! I've got some feedback for ya, hope you find it helpful!

https://youtu.be/XAkWRA_Gixk

**Comment by leeovery** [comment]
Thank you so much....!!!!!

(see what I did there lol) (did it again) 🤣 

Seriously though, thank you very much. Really appreciate the feedback. I will get to work after Ive finishing dicking about with MailCoach haha.

Lee

**Comment by jackmcdade** [comment]
My pleasure. Hope it moves the needle for ya!
