### ISSUE TITLE
Jay George Homepage

### ISSUE THREAD

**Issue by jaygeorge** [jackmcdade/five-minute-feedback#5]
https://jaygeorge.co.uk (homepage)

Hey Jack, I've recently been trying to redesign my homepage and in typical fashion, I've found that designing for myself is the most difficult!

Originally I started designing an "online CV" but it sort of morphed into a new homepage.
The page is mainly to sell myself as a nice human to work with more than just an "I'm another web designer" website—hence the "Intrigue" section.

It might help to tell you what I think is working…

I'm quite happy with the top intro and description area and I am mostly satisfied from the "Knowledge" heading downwards.

So, I am mainly struggling with the middle third of the page—say between the three icon illustrations at the top to the paragraph before the "Knowledge" heading.

I feel like the middle third is not as visually strong as the bottom section and rides a half-way house between clean/modern and skeuomorphism aesthetic, what with the grungy texture. So my initial self-critique is to get rid of the textured stuff in the middle—although I do like the subtle background texture at the very top of the page—and then re-model the middle to be more like the bottom. 

I have a couple of other thoughts but don't want to load you too much! I am mainly curious what you think as another designer since I am freelance so I don't receive critique enough.

Please be savage :-D — I need to hear honest but constructive feedback. I've tried asking on Twitter but people just want to be nice.

**Comment by jackmcdade** [comment]
Happy to help! Before I make some suggestions, how do you feel about humor? Do you want to keep the serious tone? If so, tell me a bit more about yourself. More than "I cook, bike, play video games".

**Comment by jaygeorge** [comment]
Haha well on the humour front I actually co-host a pretty dark-humoured video game podcast called "I Don't Have Time To Game Anymore" https://idonthavetimetogameanymore.com (not for the easily offended). So I have no problem making it lighter!

Historically I've never really cooked for myself and so I have terrible frozen-food habits. I'm trying to dig myself out of this hole, trying out veganism and building a cooking and recipe planner in my spare time to improve my discipline—not functional at the moment, but WIP is https://vee.guide. It's so much more enjoyable to cook knowing that I can build a website to help me with it.

I don't really love cycling recreationally but I have a zippy road bike to cycle 11 miles into central London a couple of days a week, which takes the same amount of time as it does travelling by train. I still find this crazy! And I feel smug in work knowing that I've just had a cardio workout and cheated time.

I play squash because I hate mindless exercising. I'm not great at the actual game but I don't care—the competition of the game makes the calorie-burning super fun!

**Comment by jaygeorge** [comment]
I've just thought that you might have wanted more career-driven info…

Let me know if you want anything else, I'm quite happy to type away if it helps your kind suggestions!

**Comment by jackmcdade** [comment]
Nah that's great, will get some feedback catapulted in your direction soon!

**Comment by jackmcdade** [comment]
I dug as deep and went as savage as I could. Enjoy! Hope it helps 👍 https://youtu.be/KX7IeH1C254
